### ISSUE TITLE
Incorrect behavior of a function

### ISSUE THREAD

**Issue by izh1** [frankiechapson/CRON-Next-Date#1]
`select F_CRON_NEXT_DATE('* 8 * * *', to_date('05.02.2019 09:10:00','dd.mm.yyyy hh24:mi:ss')) from dual`
Result:
05.02.2019 08:00
Next cron date must be:
06.02.2019 08:00

or

`select sysdate, F_CRON_NEXT_DATE('* 7 8 2 *', sysdate) next_run from dual`
09.02.2019 10:57:27
08.03.2019 7:00:00

Next cron date must be:
08.02.2020 7:00:00

**Comment by frankiechapson** [comment]
fixed
