### ISSUE TITLE
function does not work correctly in all circumstances -> find crorrected coding here

### ISSUE THREAD

**Issue by alois-vogl** [frankiechapson/CRON-Next-Date#2]
for example:
Select f_cron_next_date('2 8 15 9 *',  to_date('15.09.2020 08:03:00', 'DD.MM.YYYY HH24:MI:SS')) from dual;
delivers:           15.09.2020 08:02:00
should deliver: 15.09.2021 08:02:00

See corrected code in attachment:

[F_CRON_NEXT_DATE.txt](https://github.com/frankiechapson/CRON-Next-Date/files/5224118/F_CRON_NEXT_DATE.txt)

**Comment by frankiechapson** [comment]
Fixed
